require_relative 'common'
require_relative 'base'
require_relative 'browser'
require_relative 'prices'
require_relative 'roles'
require_relative 'sub_roles'
require_relative 'ten_ton_tiers'
require_relative 'icy_veins_builds'
require_relative 'icy_veins_tiers'
require_relative 'icy_veins_maps'
require_relative 'icy_veins_synergies_counters'
require_relative 'win_percent'
require_relative 'map_compositions'

require_relative 'parsers/hots_api_export'
require_relative 'parsers/hero'
require_relative 'parsers/hero_talents'
require_relative 'parsers/composition_stat'
require_relative 'parsers/hots_logs_export/replay_processor'
require_relative 'parsers/hots_logs_export/parser'


